# Defines object locations as [x, y, theta] in the robot's frame for a bunch of tasks
# --- MoveTo ---
Station A: [2.0, -0.5, 0.0]
Station B: [0.0, 2.0, 0.0]
Station C: [-2.0, 0.0, 0.0]
Station D: [0.0, -2.0, 0.0]
Station E: [1.0, 3.0, 0.0]
Station F: [-3.0, -1.0, 0.0]
Station G: [0.5, 2.0, 0.0]
Station H: [1.0, 2.0, 0.0]
Station I: [2.0, 0.5, 0.0]
Station J: [2.0, -1.0, 0.0]
Station K: [2.0, 1.0, 0.0]
Station L: [2.0, -3.0, 0.0]
Station M: [0.0, 0.5, 0.0]
Station N: [0.0, -3.0, 0.0]
Parking: [0.5, 0.0, 0.0]
Aruco Stand: [-1.6, 3.0, 0.0]
# --- MoveToWithTimeout ---
Point A: [3.0, -1.0, 0.0]
Point B: [1.8, -1.2, 0.0]
Point C: [1.0, -1.0, 0.0]
